name: recipes
services:
  mongo:
    image: mongo:8
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: >
        echo "try { rs.status() } catch (err) { 
          rs.initiate({
            _id: 'rs0', 
            members: [{ _id: 0, host: 'host.docker.internal:27017' }]
          }) 
        }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 10s
      retries: 30
  redis:
    image: redis:8.6
    restart: unless-stopped              
    ports:
      - "6379:6379"              
    volumes:
      - redis-data:/data
  redis-insight:
    image: redis/redisinsight:3.2
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
volumes:
  mongo-data:
  redis-data:
  redis-insight-data: