name: recipes
services:
  mongo:
    image: mongo:8.0
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: >
        echo "try { rs.status() } catch (err) { 
          rs.initiate({
            _id: 'rs0', 
            members: [{ _id: 0, host: 'host.docker.internal:27017' }]
          }) 
        }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 10s
      retries: 30
      
  redis:
    image: redis:8.6
    restart: unless-stopped
    command: ["redis-server", "--aclfile", "/etc/redis/users.acl"]
    ports:
      - "6379:6379"              
    volumes:
      - redis-data:/data
      - ./redis/users.acl:/etc/redis/users.acl
  
  redis-sessions:
    image: redis:8.6
    restart: unless-stopped
    command: ["redis-server", "--aclfile", "/etc/redis/users.acl"]              
    ports:
      - "6380:6379"              
    volumes:
      - redis-sessions-data:/data
      - ./redis/users.acl:/etc/redis/users.acl

  redis-insight:
    image: redis/redisinsight:3.2
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
      - redis-sessions

  rabbitmq:
    image: rabbitmq:3.13.7-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    ports:
      - "9000:9000"    # API / S3 endpoint
      - "9001:9001"    # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Tr0ub4dor&3@792041856321948576
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=es-local-cluster
      - node.name=es-local
    volumes:
      - elastic-search-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  redis-data:
  redis-sessions-data:
  redis-insight-data:
  minio-data:
  elastic-search-data:
  rabbitmq-data: